#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mcally.UI.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Welcome.cshtml")]
    public partial class _Views_Home_Welcome_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Welcome_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Home\Welcome.cshtml"
  
    ViewBag.Title = "Welcome";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Welcome</h2>\r\n\r\n<div>\r\n    <h1>欢迎来到Mcally 的管理系统界面</h1>\r\n\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
