#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mcally.UI.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/MainHtml.cshtml")]
    public partial class _Views_Home_MainHtml_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_MainHtml_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh\"");

WriteLiteral(" xmlns:th=\"http://www.thymeleaf.org\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"renderer\"");

WriteLiteral(" content=\"webkit\"");

WriteLiteral(">\r\n    <title>Mcally管理系统首页</title>\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(" content=\"Mcally管理系统首页\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"Mcally管理系统首页\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 375), Tuple.Create("\"", 413)
, Tuple.Create(Tuple.Create("", 382), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/bootstrap.min.css")
, 382), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 445), Tuple.Create("\"", 486)
, Tuple.Create(Tuple.Create("", 452), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/font-awesome.min.css")
, 452), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 518), Tuple.Create("\"", 550)
, Tuple.Create(Tuple.Create("", 525), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/animate.css")
, 525), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 582), Tuple.Create("\"", 612)
, Tuple.Create(Tuple.Create("", 589), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/style.css")
, 589), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 644), Tuple.Create("\"", 680)
, Tuple.Create(Tuple.Create("", 651), Tuple.Create<System.Object, System.Int32>(Href("~/Content/ruoyi/css/ry-ui.css")
, 651), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        .nav > li:hover .dropdown-menu {
            display: block;
        }

        #content-main.max {
            height: calc(100% - 110px);
            overflow: hidden;
            width: 100%;
            height: 100%;
            left: 0px;
            position: absolute;
            top: 0px;
            z-index: 9998;
            margin: 0;
        }
    </style>
</head>
<body");

WriteLiteral(" class=\"fixed-sidebar full-height-layout gray-bg\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\r\n\r\n        <!--左侧导航开始-->\r\n        <nav");

WriteLiteral(" class=\"navbar-default navbar-static-side\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"nav-close\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-times-circle\"");

WriteLiteral("></i>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"sidebar-collapse\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav\"");

WriteLiteral(" id=\"side-menu\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"dropdown profile-element\"");

WriteLiteral(">\r\n                            <span>\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1729), Tuple.Create("\"", 1757)
, Tuple.Create(Tuple.Create("", 1735), Tuple.Create<System.Object, System.Int32>(Href("~/Content/img/user.png")
, 1735), false)
);

WriteLiteral(" alt=\"image\"");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(" height=\"60\"");

WriteLiteral(" width=\"60\"");

WriteLiteral(" />\r\n                            </span>\r\n                            <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"block m-t-xs\"");

WriteLiteral("><strong");

WriteLiteral(" class=\"font-bold\"");

WriteLiteral(">用户</strong></span>\r\n                                    <span");

WriteLiteral(" class=\"text-muted text-xs block\"");

WriteLiteral("><span>部门</span> <b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b></span>\r\n                                </span>\r\n                          " +
"  </a>\r\n                            <ul");

WriteLiteral(" class=\"dropdown-menu animated fadeInRight m-t-xs\"");

WriteLiteral(">\r\n                                <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(">个人信息</a></li>\r\n                                <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                                <li><a");

WriteLiteral(" href=\"/Home/Index\"");

WriteLiteral(">退出</a></li>\r\n                            </ul>\r\n                        </div>\r\n" +
"                    </li>\r\n                    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"index.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i> <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">主页</span> <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"/Home/index3\"");

WriteLiteral(">了解Mcally</a></li>\r\n                        </ul>\r\n                    </li>\r\n   " +
"                 <li>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa fa-bar-chart-o\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">一级菜单</span>\r\n                            <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n                            <li>\r\n\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n                                <ul");

WriteLiteral(" class=\"nav nav-third-level\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"/Home/Index4\"");

WriteLiteral(">三级菜单</a></li>\r\n                                </ul>\r\n                          " +
"  </li>\r\n                            <li>\r\n\r\n                                <a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"/Home/Index2\"");

WriteLiteral(">二级菜单V2</a>\r\n\r\n                            </li>\r\n                            <li" +
">\r\n                                <a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"/Home/Index3\"");

WriteLiteral(">二级菜单V3</a>\r\n                            </li>\r\n\r\n                        </ul>\r\n" +
"                    </li>\r\n                    <li>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa fa-bar-chart-o\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">一级菜单</span>\r\n                            <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n                            <li>\r\n\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n                                <ul");

WriteLiteral(" class=\"nav nav-third-level\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n                                    <li>\r\n                       " +
"                 <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">三级菜单</span>\r\n                                            <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span>\r\n                                        </a>\r\n                         " +
"               <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n                                            <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">四级菜单</a></li>\r\n                                        </ul>\r\n                  " +
"                  </li>\r\n\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n\r\n                                </ul>\r\n                        " +
"    </li>\r\n                            <li>\r\n\r\n                                <" +
"a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单V2</a>\r\n\r\n                            </li>\r\n                            <li" +
">\r\n\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单V3</a>\r\n\r\n                            </li>\r\n                        </ul>\r\n" +
"                    </li>\r\n                    <li>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa fa-bar-chart-o\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">一级菜单</span>\r\n                            <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n                                <ul");

WriteLiteral(" class=\"nav nav-third-level\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n                                </ul>\r\n                          " +
"  </li>\r\n                        </ul>\r\n                    </li>\r\n             " +
"       <li>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa fa-bar-chart-o\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">一级菜单</span>\r\n                            <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n                                <ul");

WriteLiteral(" class=\"nav nav-third-level\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n                                </ul>\r\n                          " +
"  </li>\r\n                        </ul>\r\n                    </li>\r\n             " +
"       <li>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa fa-bar-chart-o\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">一级菜单</span>\r\n                            <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n                                <ul");

WriteLiteral(" class=\"nav nav-third-level\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">三级菜单</a></li>\r\n                                </ul>\r\n                          " +
"  </li>\r\n                        </ul>\r\n                    </li>\r\n             " +
"       <li>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa fa-bar-chart-o\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">一级菜单</span>\r\n                            <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span>\r\n                        </a>\r\n                        <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">二级菜单<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n                                <ul");

WriteLiteral(" class=\"nav nav-third-level\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" class=\"menuItem\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(@">三级菜单</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div");

WriteLiteral(" id=\"page-wrapper\"");

WriteLiteral(" class=\"gray-bg dashbard-1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row border-bottom\"");

WriteLiteral(">\r\n                <nav");

WriteLiteral(" class=\"navbar navbar-static-top\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral("\r\n                     style=\"margin-bottom: 0\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n\r\n                        <a");

WriteLiteral(" class=\"navbar-minimalize minimalize-styl-2 btn btn-default \"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"收起菜单\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral("></i>\r\n                        </a>\r\n                    </div>\r\n                " +
"    <ul");

WriteLiteral(" class=\"nav navbar-top-links navbar-right welcome-message\"");

WriteLiteral(">\r\n                        <li>\r\n                            <span");

WriteLiteral(" class=\"m-r-sm text-muted\"");

WriteLiteral(">欢迎来到Mcally管理后台.</span>\r\n                        </li>\r\n                        <" +
"li><a");

WriteLiteral(" id=\"fullScreen\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-arrows-alt\"");

WriteLiteral("></i>全屏</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"/Home/Index\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-sign-out\"");

WriteLiteral("></i>退出</a></li>\r\n                    </ul>\r\n                </nav>\r\n            " +
"</div>\r\n            <div");

WriteLiteral(" class=\"row content-tabs\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"roll-nav roll-left tabLeft\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-backward\"");

WriteLiteral("></i>\r\n                </button>\r\n                <nav");

WriteLiteral(" class=\"page-tabs menuTabs\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"page-tabs-content\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"active menuTab\"");

WriteLiteral(" data-id=\"/Home/Welcome\"");

WriteLiteral(">首页</a>\r\n                    </div>\r\n                </nav>\r\n                <but" +
"ton");

WriteLiteral(" class=\"roll-nav roll-right tabRight\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-forward\"");

WriteLiteral("></i>\r\n                </button>\r\n                <div");

WriteLiteral(" class=\"btn-group roll-nav roll-right\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"dropdown J_tabClose\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n                        页签操作<span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <ul");

WriteLiteral(" role=\"menu\"");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(">\r\n                        <li><a");

WriteLiteral(" class=\"tabCloseCurrent\"");

WriteLiteral(" href=\"javascript:void();\"");

WriteLiteral(">关闭当前</a></li>\r\n                        <li><a");

WriteLiteral(" class=\"tabCloseOther\"");

WriteLiteral(" href=\"javascript:void();\"");

WriteLiteral(">关闭其他</a></li>\r\n                        <li><a");

WriteLiteral(" class=\"tabCloseAll\"");

WriteLiteral(" href=\"javascript:void();\"");

WriteLiteral(">全部关闭</a></li>\r\n                        <li><a");

WriteLiteral(" class=\"tabMaxCurrent\"");

WriteLiteral(" href=\"javascript:void();\"");

WriteLiteral(">全屏显示</a></li>\r\n                    </ul>\r\n                </div>\r\n              " +
"  <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"roll-nav roll-right tabReload\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-refresh\"");

WriteLiteral("></i> 刷新</a>\r\n            </div>\r\n\r\n            <a");

WriteLiteral(" id=\"ax_close_max\"");

WriteLiteral(" class=\"ax_close_max\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"关闭全屏\"");

WriteLiteral("> <i");

WriteLiteral(" class=\"fa fa-times-circle-o\"");

WriteLiteral("></i> </a>\r\n\r\n            <div");

WriteLiteral(" class=\"row mainContent\"");

WriteLiteral(" id=\"content-main\"");

WriteLiteral(">\r\n                <iframe");

WriteLiteral(" class=\"RuoYi_iframe\"");

WriteLiteral(" name=\"iframe0\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" height=\"100%\"");

WriteLiteral(" data-id=\"/Home/index2\"");

WriteLiteral("\r\n                        frameborder=\"0\"");

WriteLiteral(" seamless></iframe>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"footer\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">© 2018 RuoYi Copyright </div>\r\n            </div>\r\n        </div>\r\n        <!--右" +
"侧部分结束-->\r\n    </div>\r\n    <!-- 全局js -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12213), Tuple.Create("\"", 12245)
, Tuple.Create(Tuple.Create("", 12219), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/js/jquery.min.js")
, 12219), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12269), Tuple.Create("\"", 12304)
, Tuple.Create(Tuple.Create("", 12275), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/js/bootstrap.min.js")
, 12275), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12328), Tuple.Create("\"", 12384)
, Tuple.Create(Tuple.Create("", 12334), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/js/plugins/metisMenu/jquery.metisMenu.js")
, 12334), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12408), Tuple.Create("\"", 12470)
, Tuple.Create(Tuple.Create("", 12414), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/js/plugins/slimscroll/jquery.slimscroll.min.js")
, 12414), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12494), Tuple.Create("\"", 12545)
, Tuple.Create(Tuple.Create("", 12500), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ajax/libs/blockUI/jquery.blockUI.js")
, 12500), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12569), Tuple.Create("\"", 12602)
, Tuple.Create(Tuple.Create("", 12575), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ruoyi/js/ry-ui.js")
, 12575), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12626), Tuple.Create("\"", 12656)
, Tuple.Create(Tuple.Create("", 12632), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ruoyi/index.js")
, 12632), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12680), Tuple.Create("\"", 12737)
, Tuple.Create(Tuple.Create("", 12686), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/ajax/libs/fullscreen/jquery.fullscreen.js")
, 12686), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"http://tajs.qq.com/stats?sId=62048022\"");

WriteLiteral("></script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
